%% function to load SMLM loccalization results of ThunderSTORM 
% Localizations = Load_ThunderSTORM(filename,is3d)
% Input: 
%    filename: the path and name of the csv file generated by ThunderSTORM
%    is3d: set 1 for 3d dataset, 0 for 2d dataset 
% Output:
%    Localizations: the extracted localization dataset for drift correction
%
function Localizations = Load_ThunderSTORM(filename,is3d)

if(is3d) % 3D dataset
    Localizations = readmatrix(filename,'Range','A:D'); % A: frame id, B: x positions, C: y positions, D: z positions.
else % 2D dataset
    Localizations = readmatrix(filename,'Range','A:C'); % A: frame id, B: x positions, C: y positions.
end
    Localizations(1,:) = [];

end

